version: "3.7"
services:
  auction-db:
    container_name: auction-db
    build: ./auction-db
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${AUCTION_DB_ROOT_PASSWORD}
      MYSQL_USER: ${AUCTION_DB_USER}
      MYSQL_PASSWORD: ${AUCTION_DB_PASSWORD}
      MYSQL_DATABASE: ${AUCTION_DB_NAME}
    ports:
      - ${AUCTION_DB_PORT}:${AUCTION_DB_PORT}
    restart: always
  
  auction-redis:
    container_name: auction-redis
    image: redis:alpine
    ports:
      - ${AUCTION_REDIS_PORT}:${AUCTION_REDIS_PORT}

  auction-api:
    container_name: auction-api
    image: node:11
    env_file:
      - ./.env
    ports:
      - ${AUCTION_API_PORT}:${AUCTION_API_PORT}
    volumes:
      - ./auction-api:/app
    working_dir: /app
    command: yarn start
    tty: true
    depends_on:
      - auction-db
      - auction-redis
    links:
      - auction-db
      - auction-redis

  contract-api:
    container_name: contract-api
    image: node:11
    env_file:
      - ./.env
    ports:
      - ${CONTRACT_API_PORT}:${CONTRACT_API_PORT}
    volumes:
      - ./contract-api:/app
    working_dir: /app
    command: >
      bash -c "yarn compile &&
      yarn migrate:ganache &&
      yarn start"
    tty: true
    depends_on:
      - ganache
    links:
      - ganache

  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    command: ["-a", "1"]
    ports:
      - ${GANACHE_PORT}:${GANACHE_PORT}
