version: "3.7"
services:
  auction_db:
    container_name: auction_db
    build: ./auction_db
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${AUCTION_DB_ROOT_PASSWORD}
      MYSQL_USER: ${AUCTION_DB_USER}
      MYSQL_PASSWORD: ${AUCTION_DB_PASSWORD}
      MYSQL_DATABASE: ${AUCTION_DB_NAME}
    ports:
      - ${AUCTION_DB_PORT}:${AUCTION_DB_PORT}
    restart: always

  auction_api:
    container_name: auction_api
    image: node:11
    env_file:
      - ./.env
    ports:
      - ${AUCTION_API_PORT}:${AUCTION_API_PORT}
    volumes:
      - ./auction_api:/app
    working_dir: /app
    command: yarn dev
    tty: true
    depends_on:
      - auction_db
    links:
      - auction_db

  contract_api:
    container_name: contract_api
    image: node:11
    env_file:
      - ./.env
    ports:
      - ${CONTRACT_API_PORT}:${CONTRACT_API_PORT}
    volumes:
      - ./contract_api:/app
    working_dir: /app
    command: >
      bash -c "yarn run compile &&
      yarn run migrate:ganache &&
      yarn start"
    tty: true
    depends_on:
      - ganache
    links:
      - ganache

  admin_web:
    container_name: admin_web
    image: node:11
    env_file:
      - ./.env
    ports:
      - ${ADMIN_WEB_PORT}:${ADMIN_WEB_PORT}
    volumes:
      - ./admin_web:/app
    working_dir: /app
    command: yarn dev
    tty: true
    depends_on:
      - auction_api
      - contract_api
    links:
      - auction_api
      - contract_api

  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    command: ["-a", "1"]
    ports:
      - ${GANACHE_PORT}:${GANACHE_PORT}
