version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - .env
    ports:
      - "3306:3306"
  app:
    image: tighug/pm:latest
    environment:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    links:
      - db
