version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Koudai123
      MYSQL_USER: tighug
      MYSQL_PASSWORD: Koudai123
    ports:
      - "3306:3306"
  app:
    image: tighug/pm:latest
    depends_on:
      - db
    ports:
      - "3000:3000"
    links:
      - db

