version: "3.7"
services:
  flow-api:
    image: tighug/achernar-flow-api
    environment:
      DB_URL: ${FLOW_DB_URL}
      REDIS_HOST: ${FLOW_REDIS_HOST}
      REDIS_PORT: ${FLOW_REDIS_PORT}
    ports:
      - ${FLOW_API_PORT}:8000
    restart: always
    depends_on:
      - flow-db

  flow-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: flow
    ports:
      - ${FLOW_DB_PORT}:3306
    restart: always
    volumes:
      - ./flow-db/initdb.d:/docker-entrypoint-initdb.d
      - ./flow-db/conf.d:/etc/mysql/conf.d

  flow-redis:
    image: redis:buster
    ports:
      - ${FLOW_REDIS_PORT}:6379
    restart: always
